version: "3.4"

services:
  web_ui:
    build: ./web_ui
    network_mode: host
    environment: 
      - BACKEND_HOST=localhost:8888
    container_name: gnxi_web_ui
  backend:
    build: 
      context: ..
      dockerfile: gnxi_tester/Dockerfile
    network_mode: host
    container_name: gnxi_backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
